cc_binary(
    name = "SolvePushbox",
    srcs = ["pushbox/SolvePushbox.cpp"],
    visibility = ["//visibility:public"],
    deps = ["//src/core:CRISP", "@piqp//:piqp_shared_lib"],
)

cc_binary(
    name = "SolvePushboxWithDrake",
    srcs = ["pushbox/SolvePushboxWithDrake.cpp"],
    visibility = ["//visibility:public"],
    deps = ["//src/core:CRISP", "@piqp//:piqp_shared_lib"],
)
