load("@drake//tools/install:install.bzl", "install")
load(
    "@drake//tools/skylark:pybind.bzl",
    "drake_pybind_library",
    "get_drake_py_installs",
    "get_pybind_package_info",
    "pybind_py_library",
)
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("@rules_python//python:packaging.bzl", "py_package")

# -*- mode: python -*-
# vi: set ft=python :
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "CRISP",
    srcs = ["src/cppad_core/CppAdInterface.cpp"],
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    linkopts = [
        "-ldl",
        "-lboost_filesystem",
        "-lboost_system",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@cppad",
        "@drake//:drake_shared_library",
    ],
)

pybind_py_library(
    name = "pyCRISP",
    cc_deps = ["//src/core:CRISP"],
    cc_so_name = "pyCRISP",
    cc_srcs = ["python/pybindSolver.cpp"],
)

# Build targets for testing
cc_binary(
    name = "test_cppad_interface",
    srcs = ["tests/test_cppad_interface.cpp"],
    visibility = ["//visibility:public"],
    deps = [":CRISP"],
)

cc_binary(
    name = "test_optimizationProblem",
    srcs = ["tests/test_optimizationProblem.cpp"],
    visibility = ["//visibility:public"],
    deps = [":CRISP"],
)

cc_binary(
    name = "test_optimizationProblemWithDrake",
    srcs = ["tests/test_optimizationProblemWithDrake.cpp"],
    visibility = ["//visibility:public"],
    deps = [":CRISP"],
)

cc_binary(
    name = "test_solver",
    srcs = ["tests/test_solver.cpp"],
    visibility = ["//visibility:public"],
    deps = [":CRISP"],
)
